Repository kubernetes-sigs/mcs-api, pull requests merged in 2023-05, with the labels that each got.

#39 update appProtocol definition based to align with k8s 1.27
  pkg/apis/v1alpha1/serviceimport.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#34 Avoid crashing while waiting for the hello pod IP
  e2etest/connectivity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#38 Upgrade to go 1.19 as 1.18 is out of support
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#40 Update golang builder image to 1.19 to stay in support
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup
