Repository kubernetes-sigs/mcs-api, pull requests merged in 2023-02, with the labels that each got.

#31 Updated ginkgo to v2.7.0
  e2etest/connectivity_test.go
  e2etest/e2e_suite_test.go
  go.mod
  go.sum
  pkg/controllers/controllers_suite_test.go
  pkg/controllers/endpointslice_test.go
  pkg/controllers/serviceimport_test.go
  scripts/e2e-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#36 Conformance suite
  conformance/conformance_suite_test.go
  conformance/connectivity_test.go
  conformance/framework.go
  conformance/k8s_objects.go
  conformance/mcs_objects.go
  conformance/report.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XL, lgtm

#35 Add constant for well-known source cluster label
  pkg/apis/v1alpha1/well_known_labels.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#33 Remove ServiceExportConditionType
  pkg/apis/v1alpha1/serviceexport.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
