Repository kubernetes-sigs/mcs-api, pull requests merged in 2024-12, with the labels that each got.

#83 Add DNS conformance tests for ClusterIP services
  conformance/clusterip_service_dns.go
  conformance/connectivity.go
  conformance/report.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#88 Avoid parsing ls to loop over files
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#86 Fail early if the MCS CRDs are not available
  conformance/conformance_suite.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#90 Output BeforeSuite failure in conformance report
  conformance/conformance_suite.go
  conformance/report.go
  conformance/report_template.gohtml
Labels: approved, cncf-cla: yes, lgtm, size/S

#89 Add connectivity conformance test involving service in two clusters
  conformance/clusterip_service_dns.go
  conformance/conformance_suite.go
  conformance/connectivity.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#87 Fix Go linting
  conformance/clusterip_service_dns.go
  conformance/conformance_suite.go
  conformance/endpoint_slice.go
  conformance/framework.go
  conformance/report.go
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#84 apis: conformance: add labels and annotation export
  config/crd/multicluster.x-k8s.io_serviceexports.yaml
  conformance/clusterip_service_dns.go
  conformance/conformance_suite.go
  conformance/connectivity.go
  conformance/endpoint_slice.go
  conformance/k8s_objects.go
  conformance/report.go
  conformance/service_import.go
  pkg/apis/v1alpha1/serviceexport.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L
