Repository kubernetes-sigs/mcs-api, pull requests merged in 2024-08, with the labels that each got.

#56 Add myself to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#53 implement test 2: local service not impacted
  e2etest/connectivity_test.go
  e2etest/e2e_suite_test.go
  e2etest/localserviceimpact_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#54 Allow codegen verification
  hack/update-codegen.sh
  pkg/client/clientset/versioned/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#55 Move tool dependencies to a separate module
  Makefile
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/verify-crds.sh
  tools/go.mod
  tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#59 Address use of deprecated functions in the conformance package
  conformance/conformance_suite.go
  conformance/framework.go
  conformance/k8s_objects.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#58 Format conformance report in HTML
  .gitignore
  conformance/connectivity_test.go
  conformance/report.go
  conformance/report_template.gohtml
Labels: approved, cncf-cla: yes, lgtm, size/L

#57 Add conformance_suite_test.go generated by ginkgo bootstrap
  conformance/conformance_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#60 Remove unused helloServiceExport var in conformance
  conformance/mcs_objects.go
Labels: approved, cncf-cla: yes, lgtm, size/S
