Repository kubernetes-sigs/mcs-api, pull requests merged in 2025-01, with the labels that each got.

#97 Update go to 1.23 and coredns to 1.11.4
  Dockerfile
  go.mod
  scripts/up.sh
  tools/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#96 conformance: fix annotations/labels test to not be exact match
  conformance/service_import.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#91 Add conformance tests for headless ServiceImport
  conformance/conformance_suite.go
  conformance/report.go
  conformance/service_import.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#99 Conformance: verify ServiceImport doesn't contain Service labels/annotations
  conformance/service_import.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#95 conformance: fix for dns test with different clusterip on each cluster
  conformance/clusterip_service_dns.go
Labels: approved, cncf-cla: yes, lgtm, size/S
